import turtle
gameloop=True
donatello = turtle.Turtle()
move=1
move=float(move)
while gameloop==True:
    
    donatello.forward(move)
    donatello.right(30)
    donatello.forward(move)
    donatello.right(30)
    donatello.forward(move)
    donatello.right(30)
    donatello.forward(move)
    donatello.right(30)
    donatello.forward(move)
    donatello.right(30)
    donatello.forward(move)
    donatello.right(30)
    donatello.forward(move)
    donatello.right(30)
    donatello.forward(move)
    donatello.right(30)
    donatello.forward(move)
    donatello.right(30)
    donatello.forward(move)
    donatello.right(30)
    donatello.forward(move)
    donatello.right(30)
    donatello.forward(move)
    donatello.right(30)
    donatello.forward(move)
    donatello.right(30)
    donatello.forward(move)
    donatello.right(30)
    donatello.forward(move)
    donatello.right(30)
    donatello.forward(move)
    donatello.right(30)
    donatello.forward(move)
    donatello.right(30)
    donatello.forward(move)
    donatello.right(30)
    donatello.forward(move)
    donatello.right(30)
    donatello.forward(move)
    donatello.right(30)
    donatello.forward(move)
    donatello.right(30)
    donatello.forward(move)
    donatello.right(30)
    donatello.forward(move)
    donatello.right(30)
    donatello.forward(move)
    donatello.right(30)
    donatello.forward(move)
    donatello.right(30)
    donatello.forward(move)
    donatello.right(30)
    donatello.forward(move)
    donatello.right(30)
    donatello.forward(move)
    donatello.right(30)
    donatello.forward(move)
    donatello.right(30)
    donatello.forward(move)
    donatello.right(30)
    
    move=move-10

    
        
